### ISSUE TITLE
Any updates with DBC support ?

### ISSUE THREAD

**Issue by chrissunny94** [GENIVI/CANdevStudio#182]
I got to understand from the documentation that the [signals](https://github.com/GENIVI/CANdevStudio/tree/signals) branch has DBC support . 

I managed to compile it and run it  .

_I am able to see CAN messages , but **not able to decode it with .dbc file**  , can someone please tell me the steps to set it up ._ 

Also , the  list down menu while selecting **CAN interface , can interface type** etc is not appearing . 
(I  had  to manually type in!)

Any pointers as to where to start would be much appreciated .

I am very happy with the tool , i hope this could be a good opensource alternative to expensive closed source softwares such as vector db++ .(Used widely in the automotive industry )

Though some fixing and additional tools would be necessary . 

I see the lack of a good GUI CAN tool kind of hindering progress in the Automotive sector , especially since  ROS came into picture  .

**Comment by rkollataj** [comment]
@chrissunny94 To get CAN signals decoded you need to pass path to the DBC file. Just right-click on CanSignalData component and choose properties. Give it a try and let me know if it worked.

Signals branch is not in sync with latest master that's why you cannot use some features that are on master branch. Rebasing signals on on top of master should help however it would require a lot of manual merging.

I am doing work on CDS in my free time that's why the progress was not significant recently. I still need to earn for a living :) I am working currently on moving CanSignalData to master branch. I hope to complete it shortly. CanSignalData is the most complex component for signal handling so remaining parts should take much less time.

Anyways I am open for contributions. If you know someone that would like to spend some time on resolving issues I would appreciate it.

**Comment by chrissunny94** [comment]
@rkollataj 

thanks it worked . 

I will try to contribute to this project in my free time .
